name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create minimal package.json
        run: |
          cat > package.json << 'EOL'
          {
            "name": "portfolio",
            "version": "0.1.0",
            "private": true,
            "scripts": {
              "dev": "next dev",
              "build": "next build",
              "start": "next start"
            },
            "dependencies": {
              "next": "13.4.19",
              "react": "18.2.0",
              "react-dom": "18.2.0"
            }
          }
          EOL
          cat package.json

      - name: Create minimal next.config.js
        run: |
          cat > next.config.js << 'EOL'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'export',
            images: {
              unoptimized: true
            }
          }
          
          module.exports = nextConfig
          EOL
          cat next.config.js

      - name: Create minimal pages structure
        run: |
          mkdir -p pages
          cat > pages/index.js << 'EOL'
          export default function Home() {
            return (
              <div style={{ padding: '2rem', textAlign: 'center' }}>
                <h1>My Portfolio</h1>
                <p>This is a placeholder page for my portfolio.</p>
              </div>
            )
          }
          EOL
          cat pages/index.js

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Prepare for deployment
        run: |
          touch out/.nojekyll
          echo "Contents of out directory:"
          ls -la out

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages

